/**
 * Warning! This code has been generated automatically.
 */
import React from "react"
import { ViewButton } from "@tolokoban/ui"
import CodeViewer from "@/components/demo/CodeViewer"
import Demo from "./painter-stars.demo"

const FOCUS = {"Detail #1":"function init(ctx: TgdContext) {\n    new TgdControllerCameraOrbit(ctx, {\n        inertiaOrbit: 1000,\n    });\n    ctx.add(new TgdPainterClear(ctx, { color: [0, 0, 0, 1] }));\n    ctx.paint();\n    tgdLoadArrayBuffer(dataURL).then((buff) => {\n        if (!buff) return;\n\n        const data = new Float32Array(buff);\n        const painter = new PainterStars(ctx, data);\n        ctx.add(\n            new TgdPainterState(ctx, {\n                blend: webglPresetBlend.alpha,\n                children: [new PainterNames(ctx), painter],\n            }),\n        );\n        ctx.paint();\n    });\n}","Class PainterStars":"export class PainterStars extends TgdPainter {\n    // Number of stars\n    private readonly count: number;\n    private readonly prg: TgdProgram;\n    private readonly vao: TgdVertexArray;\n\n    private readonly fixedCamera = new TgdCameraPerspective({\n        transfo: { distance: 0 },\n        near: 0.1,\n        far: 2.0,\n        fovy: Math.PI / 3,\n    });\n\n    /**\n     * @param data A sequence of 4 floats: longitude, latitude, brightness and color.\n     */\n    constructor(\n        private readonly context: TgdContext,\n        data: Float32Array,\n    ) {\n        super();\n        this.count = data.length >> 2;\n        this.prg = new TgdProgram(context.gl, {\n            vert,\n            frag,\n        });\n        const dataset = new TgdDataset({\n            attStar: \"vec4\",\n        });\n        dataset.set(\"attStar\", data);\n        this.vao = new TgdVertexArray(context.gl, this.prg, [dataset]);\n    }\n\n    paint() {\n        const { context, prg, vao, fixedCamera } = this;\n        const { camera, gl } = context;\n        fixedCamera.transfo.orientation = camera.transfo.orientation;\n        prg.use();\n        prg.uniformMatrix4fv(\"uniModelViewMatrix\", fixedCamera.matrixModelView);\n        prg.uniformMatrix4fv(\n            \"uniProjectionMatrix\",\n            fixedCamera.matrixProjection,\n        );\n        prg.uniform1f(\n            \"uniVegaSizeInPixels\",\n            Math.max(context.width, context.height) * 0.05,\n        );\n        vao.bind();\n        gl.drawArrays(gl.POINTS, 0, this.count);\n    }\n\n    delete() {\n        this.prg.delete();\n        this.vao.delete();\n    }\n}"}
const FULL = "import {\n    TgdCameraPerspective,\n    type TgdContext,\n    TgdControllerCameraOrbit,\n    TgdDataset,\n    tgdLoadArrayBuffer,\n    TgdPainter,\n    TgdPainterClear,\n    TgdPainterState,\n    TgdProgram,\n    TgdVertexArray,\n    webglPresetBlend,\n} from \"@tolokoban/tgd\";\n\nimport View from \"@/components/demo/Tgd\";\nimport dataURL from \"../stars.dat\";\nimport { PainterNames } from \"./painter-names\";\nimport frag from \"./painter-stars.frag\";\nimport vert from \"./painter-stars.vert\";\n\nfunction init(ctx: TgdContext) {\n    new TgdControllerCameraOrbit(ctx, {\n        inertiaOrbit: 1000,\n    });\n    ctx.add(new TgdPainterClear(ctx, { color: [0, 0, 0, 1] }));\n    ctx.paint();\n    tgdLoadArrayBuffer(dataURL).then((buff) => {\n        if (!buff) return;\n\n        const data = new Float32Array(buff);\n        const painter = new PainterStars(ctx, data);\n        ctx.add(\n            new TgdPainterState(ctx, {\n                blend: webglPresetBlend.alpha,\n                children: [new PainterNames(ctx), painter],\n            }),\n        );\n        ctx.paint();\n    });\n}\n\nexport default function Demo() {\n    return <View onReady={init} />;\n}\n\nexport class PainterStars extends TgdPainter {\n    // Number of stars\n    private readonly count: number;\n    private readonly prg: TgdProgram;\n    private readonly vao: TgdVertexArray;\n\n    private readonly fixedCamera = new TgdCameraPerspective({\n        transfo: { distance: 0 },\n        near: 0.1,\n        far: 2.0,\n        fovy: Math.PI / 3,\n    });\n\n    /**\n     * @param data A sequence of 4 floats: longitude, latitude, brightness and color.\n     */\n    constructor(\n        private readonly context: TgdContext,\n        data: Float32Array,\n    ) {\n        super();\n        this.count = data.length >> 2;\n        this.prg = new TgdProgram(context.gl, {\n            vert,\n            frag,\n        });\n        const dataset = new TgdDataset({\n            attStar: \"vec4\",\n        });\n        dataset.set(\"attStar\", data);\n        this.vao = new TgdVertexArray(context.gl, this.prg, [dataset]);\n    }\n\n    paint() {\n        const { context, prg, vao, fixedCamera } = this;\n        const { camera, gl } = context;\n        fixedCamera.transfo.orientation = camera.transfo.orientation;\n        prg.use();\n        prg.uniformMatrix4fv(\"uniModelViewMatrix\", fixedCamera.matrixModelView);\n        prg.uniformMatrix4fv(\n            \"uniProjectionMatrix\",\n            fixedCamera.matrixProjection,\n        );\n        prg.uniform1f(\n            \"uniVegaSizeInPixels\",\n            Math.max(context.width, context.height) * 0.05,\n        );\n        vao.bind();\n        gl.drawArrays(gl.POINTS, 0, this.count);\n    }\n\n    delete() {\n        this.prg.delete();\n        this.vao.delete();\n    }\n}\n"

export default function DemoContainer() {
    const [full, setFull] = React.useState(false)
    return <>
        <div className="half-left"><Demo /></div>
        <div className="half-right">
            <div>
                <ViewButton variant="elevated" onClick={() => setFull(!full)}>
                    {full ? "Show code details" : "Show full code"}
                </ViewButton>
            </div>
            <CodeViewer language="tsx" value={full ? FULL : FOCUS} />
        </div>
    </>
}