/**
 * Warning! This code has been generated automatically.
 */
import React from "react"
import { ViewButton } from "@tolokoban/ui"
import CodeViewer from "@/components/demo/CodeViewer"
import Demo from "./main.demo"

const FOCUS = {"Detail #1":"function init(context: TgdContext, assets: Assets) {\n\tconst { camera } = context\n\tif (camera instanceof TgdCameraPerspective) {\n\t\tcamera.near = 0.1\n\t\tcamera.far = 10\n\t}\n\tcamera.fitSpaceAtTarget(2.2, 2.2)\n\tconst uniformCamera = new TgdUniformBufferObjectCamera(context)\n\tconst clear = new TgdPainterClear(context, { color: [0, 0, 0, 1], depth: 1 })\n\tconst texture = new TgdTexture2D(context).loadBitmap(assets.image.texture)\n\tconst material = new TgdMaterialDiffuse({\n\t\tlockLightsToCamera: true,\n\t\tcolor: texture,\n\t\tambient: new TgdLight({\n\t\t\tcolor: [0.5, 0.4, 0.3, 1],\n\t\t}),\n\t})\n\tconst meshes: TgdPainterMesh[] = []\n\tconst S = 0.6\n\tfor (const x of [-S, +S]) {\n\t\tfor (const y of [-S, +S]) {\n\t\t\tfor (const z of [-S, +S]) {\n\t\t\t\tmeshes.push(\n\t\t\t\t\tnew TgdPainterMesh(context, {\n\t\t\t\t\t\tuniformCamera,\n\t\t\t\t\t\tmaterial,\n\t\t\t\t\t\ttransfo: {\n\t\t\t\t\t\t\tposition: [x, y, z],\n\t\t\t\t\t\t},\n\t\t\t\t\t}),\n\t\t\t\t)\n\t\t\t}\n\t\t}\n\t}\n\tconst gizmo = new TgdPainterGizmo(context, { size: 128 })\n\tgizmo.eventTap.addListener((evt) =>\n\t\tconsole.log(\"🐞 [main.demo@41] evt =\", evt),\n\t)\n\tcontext.add(\n\t\tclear,\n\t\t() => {\n\t\t\tuniformCamera.updateData()\n\t\t},\n\t\tnew TgdPainterState(context, {\n\t\t\tdepth: \"less\",\n\t\t\tcull: \"back\",\n\t\t\tchildren: meshes,\n\t\t}),\n\t\tnew TgdPainterState(context, {\n\t\t\tdepth: \"off\",\n\t\t\tblend: \"alpha\",\n\t\t\tchildren: [gizmo],\n\t\t}),\n\t)\n\tcontext.paint()\n\n\treturn ({\n\t\tsize,\n\t\talignY,\n\t\tresolution,\n\t}: {\n\t\tsize: number\n\t\talignY: number\n\t\tresolution: number\n\t}) => {\n\t\tgizmo.size = size\n\t\tgizmo.alignY = alignY\n\t\tcontext.resolution = resolution\n\t\tcontext.paint()\n\t}\n}"}
const FULL = "import {\n\tTgdCameraPerspective,\n\ttype TgdContext,\n\tTgdLight,\n\tTgdMaterialDiffuse,\n\tTgdPainterClear,\n\tTgdPainterGizmo,\n\tTgdPainterMesh,\n\tTgdPainterState,\n\tTgdTexture2D,\n\tTgdUniformBufferObjectCamera,\n\ttgdCalcMapRange,\n} from \"@tolokoban/tgd\"\nimport TextureURL from \"@/assets/image/uv-grid-2x2.webp\"\nimport View, { Assets } from \"@/components/demo/Tgd\"\n\nfunction init(context: TgdContext, assets: Assets) {\n\tconst { camera } = context\n\tif (camera instanceof TgdCameraPerspective) {\n\t\tcamera.near = 0.1\n\t\tcamera.far = 10\n\t}\n\tcamera.fitSpaceAtTarget(2.2, 2.2)\n\tconst uniformCamera = new TgdUniformBufferObjectCamera(context)\n\tconst clear = new TgdPainterClear(context, { color: [0, 0, 0, 1], depth: 1 })\n\tconst texture = new TgdTexture2D(context).loadBitmap(assets.image.texture)\n\tconst material = new TgdMaterialDiffuse({\n\t\tlockLightsToCamera: true,\n\t\tcolor: texture,\n\t\tambient: new TgdLight({\n\t\t\tcolor: [0.5, 0.4, 0.3, 1],\n\t\t}),\n\t})\n\tconst meshes: TgdPainterMesh[] = []\n\tconst S = 0.6\n\tfor (const x of [-S, +S]) {\n\t\tfor (const y of [-S, +S]) {\n\t\t\tfor (const z of [-S, +S]) {\n\t\t\t\tmeshes.push(\n\t\t\t\t\tnew TgdPainterMesh(context, {\n\t\t\t\t\t\tuniformCamera,\n\t\t\t\t\t\tmaterial,\n\t\t\t\t\t\ttransfo: {\n\t\t\t\t\t\t\tposition: [x, y, z],\n\t\t\t\t\t\t},\n\t\t\t\t\t}),\n\t\t\t\t)\n\t\t\t}\n\t\t}\n\t}\n\tconst gizmo = new TgdPainterGizmo(context, { size: 128 })\n\tgizmo.eventTap.addListener((evt) =>\n\t\tconsole.log(\"🐞 [main.demo@41] evt =\", evt),\n\t)\n\tcontext.add(\n\t\tclear,\n\t\t() => {\n\t\t\tuniformCamera.updateData()\n\t\t},\n\t\tnew TgdPainterState(context, {\n\t\t\tdepth: \"less\",\n\t\t\tcull: \"back\",\n\t\t\tchildren: meshes,\n\t\t}),\n\t\tnew TgdPainterState(context, {\n\t\t\tdepth: \"off\",\n\t\t\tblend: \"alpha\",\n\t\t\tchildren: [gizmo],\n\t\t}),\n\t)\n\tcontext.paint()\n\n\treturn ({\n\t\tsize,\n\t\talignY,\n\t\tresolution,\n\t}: {\n\t\tsize: number\n\t\talignY: number\n\t\tresolution: number\n\t}) => {\n\t\tgizmo.size = size\n\t\tgizmo.alignY = alignY\n\t\tcontext.resolution = resolution\n\t\tcontext.paint()\n\t}\n}\n\nexport default function Demo() {\n\treturn (\n\t\t<View\n\t\t\tonReady={init}\n\t\t\tcontroller={{\n\t\t\t\tinertiaOrbit: 1000,\n\t\t\t}}\n\t\t\toptions={{\n\t\t\t\tpreserveDrawingBuffer: true,\n\t\t\t\talpha: false,\n\t\t\t\tantialias: true,\n\t\t\t\tpremultipliedAlpha: false,\n\t\t\t}}\n\t\t\tassets={{ image: { texture: TextureURL } }}\n\t\t\tsettings={{\n\t\t\t\tsize: {\n\t\t\t\t\tlabel: \"size\",\n\t\t\t\t\tvalue: 128,\n\t\t\t\t\tmin: 64,\n\t\t\t\t\tmax: 512,\n\t\t\t\t},\n\t\t\t\talignY: {\n\t\t\t\t\tlabel: \"alignY\",\n\t\t\t\t\tvalue: 1,\n\t\t\t\t\tmin: -1,\n\t\t\t\t\tmax: +1,\n\t\t\t\t},\n\t\t\t\tresolution: {\n\t\t\t\t\tlabel: \"resolution\",\n\t\t\t\t\tvalue: 1,\n\t\t\t\t\tmin: 0.1,\n\t\t\t\t\tmax: 2,\n\t\t\t\t\tstep: 0.1,\n\t\t\t\t},\n\t\t\t}}\n\t\t/>\n\t)\n}\n"

export default function DemoContainer() {
    const [full, setFull] = React.useState(false)
    return <>
        <div className="half-left"><Demo /></div>
        <div className="half-right">
            <div>
                <ViewButton variant="elevated" onClick={() => setFull(!full)}>
                    {full ? "Show code details" : "Show full code"}
                </ViewButton>
            </div>
            <CodeViewer language="tsx" value={full ? FULL : FOCUS} />
        </div>
    </>
}