/**
 * Warning! This code has been generated automatically.
 */
import React from "react"
import { ViewButton } from "@tolokoban/ui"
import CodeViewer from "@/components/demo/CodeViewer"
import Demo from "./bricks.demo"

const FOCUS = {"Detail #1":"function init(context: TgdContext, assets: Assets) {\n    const clear = new TgdPainterClear(context, {\n        color: [0.3, 0.3, 0.3, 1],\n        depth: 1,\n    });\n    const texture = new TgdTexture2D(context, {\n        load: assets.image.sprites,\n    });\n    const cell = (col: number, row: number) => ({\n        x: col / 2,\n        y: row / 4,\n        width: 1 / 2,\n        height: 1 / 4,\n    });\n    const atlas: TgdPainterSpritesAtlas = [];\n    for (let col = 0; col < 2; col++) {\n        for (let row = 0; row < 3; row++) {\n            atlas.push(cell(col, row));\n        }\n    }\n    const spritesPainter = new TgdPainterSpritesHue(context, {\n        texture,\n        atlas,\n        atlasUnit: 2,\n    });\n    const bricks = new Map<string, TgdSprite>();\n    const click = (x: number, y: number) => {\n        const { aspectRatio } = context;\n        x *= aspectRatio > 1 ? aspectRatio : 1;\n        if (x < -1 || x > 1) return;\n\n        y *= aspectRatio > 1 ? 1 : aspectRatio;\n        if (y < -1 || y > 1) return;\n\n        x = Math.floor(x * 2) * 2 + 1;\n        y = Math.floor(y * 4) + 0.5;\n        const key = `${x}/${y}`;\n        const currentBrick = bricks.get(key);\n        if (currentBrick) {\n            if (currentBrick.index < 4) currentBrick.index++;\n            else {\n                console.log(\n                    \"Delete:\",\n                    currentBrick,\n                );\n                spritesPainter.spriteDelete(currentBrick);\n                bricks.delete(key);\n            }\n        } else {\n            const brick = spritesPainter.spriteCreate({\n                x,\n                y,\n                hue: Math.random() * .8,\n            });\n            bricks.set(key, brick);\n        }\n        context.paint();\n    };\n    for (let loop = 0; loop < 10; loop++) {\n        click(tgdCalcRandom(-1, +1), tgdCalcRandom(-1, +1));\n    }\n    context.inputs.pointer.eventTap.addListener((evt) => click(evt.x, evt.y));\n    context.add(\n        clear,\n        new TgdPainterState(context, {\n            depth: webglPresetDepth.less,\n            blend: webglPresetBlend.alpha,\n            children: [spritesPainter],\n        }),\n        new TgdPainterLogic(() => {\n            context.camera.fitSpaceAtTarget(8, 8);\n        }),\n    );\n    context.paint();\n}"}
const FULL = "import {\n    tgdCalcRandom,\n    type TgdContext,\n    TgdPainterClear,\n    TgdPainterLogic,\n    TgdPainterSprites,\n    TgdPainterSpritesAtlas,\n    TgdPainterSpritesHue,\n    TgdPainterState,\n    TgdSprite,\n    TgdTexture2D,\n    webglPresetBlend,\n    webglPresetDepth,\n} from \"@tolokoban/tgd\";\n\nimport View, { type Assets } from \"@/components/demo/Tgd\";\n\nimport BricksURL from \"./bricks.webp\";\n\nfunction init(context: TgdContext, assets: Assets) {\n    const clear = new TgdPainterClear(context, {\n        color: [0.3, 0.3, 0.3, 1],\n        depth: 1,\n    });\n    const texture = new TgdTexture2D(context, {\n        load: assets.image.sprites,\n    });\n    const cell = (col: number, row: number) => ({\n        x: col / 2,\n        y: row / 4,\n        width: 1 / 2,\n        height: 1 / 4,\n    });\n    const atlas: TgdPainterSpritesAtlas = [];\n    for (let col = 0; col < 2; col++) {\n        for (let row = 0; row < 3; row++) {\n            atlas.push(cell(col, row));\n        }\n    }\n    const spritesPainter = new TgdPainterSpritesHue(context, {\n        texture,\n        atlas,\n        atlasUnit: 2,\n    });\n    const bricks = new Map<string, TgdSprite>();\n    const click = (x: number, y: number) => {\n        const { aspectRatio } = context;\n        x *= aspectRatio > 1 ? aspectRatio : 1;\n        if (x < -1 || x > 1) return;\n\n        y *= aspectRatio > 1 ? 1 : aspectRatio;\n        if (y < -1 || y > 1) return;\n\n        x = Math.floor(x * 2) * 2 + 1;\n        y = Math.floor(y * 4) + 0.5;\n        const key = `${x}/${y}`;\n        const currentBrick = bricks.get(key);\n        if (currentBrick) {\n            if (currentBrick.index < 4) currentBrick.index++;\n            else {\n                console.log(\n                    \"Delete:\",\n                    currentBrick,\n                );\n                spritesPainter.spriteDelete(currentBrick);\n                bricks.delete(key);\n            }\n        } else {\n            const brick = spritesPainter.spriteCreate({\n                x,\n                y,\n                hue: Math.random() * .8,\n            });\n            bricks.set(key, brick);\n        }\n        context.paint();\n    };\n    for (let loop = 0; loop < 10; loop++) {\n        click(tgdCalcRandom(-1, +1), tgdCalcRandom(-1, +1));\n    }\n    context.inputs.pointer.eventTap.addListener((evt) => click(evt.x, evt.y));\n    context.add(\n        clear,\n        new TgdPainterState(context, {\n            depth: webglPresetDepth.less,\n            blend: webglPresetBlend.alpha,\n            children: [spritesPainter],\n        }),\n        new TgdPainterLogic(() => {\n            context.camera.fitSpaceAtTarget(8, 8);\n        }),\n    );\n    context.paint();\n}\n\nexport default function Demo() {\n    return (\n        <View\n            onReady={init}\n            assets={{\n                image: { sprites: BricksURL },\n            }}\n        />\n    );\n}\n"

export default function DemoContainer() {
    const [full, setFull] = React.useState(false)
    return <>
        <div className="half-left"><Demo /></div>
        <div className="half-right">
            <div>
                <ViewButton variant="elevated" onClick={() => setFull(!full)}>
                    {full ? "Show code details" : "Show full code"}
                </ViewButton>
            </div>
            <CodeViewer language="tsx" value={full ? FULL : FOCUS} />
        </div>
    </>
}