/**
 * Warning! This code has been generated automatically.
 */
import React from "react"
import { ViewButton } from "@tolokoban/ui"
import CodeViewer from "@/components/demo/CodeViewer"
import Demo from "./main.demo"

const FOCUS = {"Detail #1":"    const camera = new TgdCameraPerspective()\n    camera.spaceWidthAtTarget = 16\n    context.camera = camera\n    const clearColor = new TgdPainterClear(context, {\n        depth: 1,\n        color: [0.1, 0.2, 0.3, 1],\n    })\n    const clearDepth = new TgdPainterClear(context, {\n        depth: 1,\n    })\n    const mesh = new TgdPainterMeshGltf(context, {\n        asset: assets.glb.suzanne,\n    })\n    const state = new TgdPainterState(context, {\n        depth: \"less\",\n        cull: \"back\",\n        children: [mesh],\n    })\n    const group = new TgdPainterGroup([clearDepth, state])\n    const angle = Math.atan(1 / camera.transfo.distance)\n    const leftCamera = camera.clone()\n    leftCamera.transfo.orbitAroundY(angle)\n    const leftEye = new TgdPainterGroupCamera(context, {\n        camera: leftCamera,\n        children: [group],\n    })\n    const rightCamera = camera.clone()\n    rightCamera.transfo.orbitAroundY(-angle)\n    const rightEye = new TgdPainterGroupCamera(context, {\n        camera: rightCamera,\n        children: [group],\n    })\n    context.add(\n        clearColor,\n        (time: number, delta: number) => {\n            mesh.transfo.setEulerRotation(0, time * 60, 0)\n        },\n        (time: number, delta: number) => {\n            const { width } = context\n            const center = width / 2\n            const size = width / 4\n            context.viewportExec(\n                () => {\n                    leftEye.paint(time, delta)\n                },\n                { x: center - size, width: 200 },\n            )\n            context.viewportExec(\n                () => {\n                    rightEye.paint(time, delta)\n                },\n                { x: center, width: 200 },\n            )\n        },\n    )\n    context.play()"}
const FULL = "import {\n    TgdCameraPerspective,\n    TgdContext,\n    TgdPainterClear,\n    TgdPainterGroup,\n    TgdPainterGroupCamera,\n    TgdPainterMeshGltf,\n    TgdPainterState,\n} from \"@tolokoban/tgd\"\nimport View, { Assets } from \"@/components/demo/Tgd\"\n\nimport SuzanneURL from \"@/assets/mesh/suzanne.glb\"\n\nfunction init(context: TgdContext, assets: Assets) {\n    const camera = new TgdCameraPerspective()\n    camera.spaceWidthAtTarget = 16\n    context.camera = camera\n    const clearColor = new TgdPainterClear(context, {\n        depth: 1,\n        color: [0.1, 0.2, 0.3, 1],\n    })\n    const clearDepth = new TgdPainterClear(context, {\n        depth: 1,\n    })\n    const mesh = new TgdPainterMeshGltf(context, {\n        asset: assets.glb.suzanne,\n    })\n    const state = new TgdPainterState(context, {\n        depth: \"less\",\n        cull: \"back\",\n        children: [mesh],\n    })\n    const group = new TgdPainterGroup([clearDepth, state])\n    const angle = Math.atan(1 / camera.transfo.distance)\n    const leftCamera = camera.clone()\n    leftCamera.transfo.orbitAroundY(angle)\n    const leftEye = new TgdPainterGroupCamera(context, {\n        camera: leftCamera,\n        children: [group],\n    })\n    const rightCamera = camera.clone()\n    rightCamera.transfo.orbitAroundY(-angle)\n    const rightEye = new TgdPainterGroupCamera(context, {\n        camera: rightCamera,\n        children: [group],\n    })\n    context.add(\n        clearColor,\n        (time: number, delta: number) => {\n            mesh.transfo.setEulerRotation(0, time * 60, 0)\n        },\n        (time: number, delta: number) => {\n            const { width } = context\n            const center = width / 2\n            const size = width / 4\n            context.viewportExec(\n                () => {\n                    leftEye.paint(time, delta)\n                },\n                { x: center - size, width: 200 },\n            )\n            context.viewportExec(\n                () => {\n                    rightEye.paint(time, delta)\n                },\n                { x: center, width: 200 },\n            )\n        },\n    )\n    context.play()\n}\n\nexport default function Demo() {\n    return (\n        <View\n            onReady={init}\n            assets={{\n                glb: {\n                    suzanne: SuzanneURL,\n                },\n            }}></View>\n    )\n}\n"

export default function DemoContainer() {
    const [full, setFull] = React.useState(false)
    return <>
        <div className="half-left"><Demo /></div>
        <div className="half-right">
            <div>
                <ViewButton variant="elevated" onClick={() => setFull(!full)}>
                    {full ? "Show code details" : "Show full code"}
                </ViewButton>
            </div>
            <CodeViewer language="tsx" value={full ? FULL : FOCUS} />
        </div>
    </>
}