/**
 * Warning! This code has been generated automatically.
 */
import React from "react"
import { ViewButton } from "@tolokoban/ui"
import CodeViewer from "@/components/demo/CodeViewer"
import Demo from "./main.demo"

const FOCUS = {"Detail #1":"function init(context: TgdContext, assets: Assets) {\n\tconst { camera } = context\n\tif (camera instanceof TgdCameraPerspective) {\n\t\tcamera.fovy = tgdCalcDegToRad(60)\n\t\tcamera.spaceHeightAtTarget = 6\n\t}\n\tcamera.near = 1e-2\n\tcamera.far = 1e2\n\tconst clear = new TgdPainterClear(context, { color: [0.3, 0.3, 0.3, 1] })\n\tconst bbox: {\n\t\tmin: Readonly<ArrayNumber3>\n\t\tmax: Readonly<ArrayNumber3>\n\t} = {\n\t\tmin: [-1, -1, -1],\n\t\tmax: [+1, +1, +1],\n\t}\n\tconst [minX, minY, minZ] = bbox.min\n\tconst [maxX, maxY, maxZ] = bbox.max\n\tconst COLORS: ArrayNumber4[] = tgdColorMakeHueWheel({\n\t\tsteps: 8,\n\t}).map((color) => [color.R, color.G, color.B, 1] as ArrayNumber4)\n\tconst levels = [0, 1, 2, 3, 4, 5]\n\tconst materials = levels.map(\n\t\t(i) =>\n\t\t\tnew TgdMaterialDiffuse({\n\t\t\t\tlockLightsToCamera: true,\n\t\t\t\tcolor: COLORS[i],\n\t\t\t}),\n\t)\n\tconst boxes = [0, 1, 2, 3, 4, 5].map(\n\t\t(i) =>\n\t\t\tnew TgdPainterMeshGltf(context, {\n\t\t\t\tasset: assets.glb.box,\n\t\t\t\tmaterial: materials[i],\n\t\t\t}),\n\t)\n\tconst lod = new TgdPainterLOD(context, {\n\t\tbbox,\n\t\tasync factory(x: number, y: number, z: number, level: number) {\n\t\t\tconst size = 2 ** -level\n\t\t\tconst sizeX = size * (maxX - minX)\n\t\t\tconst sizeY = size * (maxY - minY)\n\t\t\tconst sizeZ = size * (maxZ - minZ)\n\t\t\tconst center: ArrayNumber3 = [\n\t\t\t\t(x + 0.5) * sizeX + minX,\n\t\t\t\t(y + 0.5) * sizeY + minY,\n\t\t\t\t(z + 0.5) * sizeZ + minZ,\n\t\t\t]\n\t\t\tconst transfo = new TgdTransfo()\n\t\t\ttransfo.setPosition(center).setScale(sizeX, sizeY, sizeZ)\n\t\t\tconst node = new TgdPainterNode({\n\t\t\t\tname: `(${x}, ${y}, ${z})/${level}`,\n\t\t\t\tchildren: [boxes[level]],\n\t\t\t\ttransfo,\n\t\t\t})\n\t\t\treturn node\n\t\t},\n\t\tsubdivisions: 5,\n\t})\n\tcontext.add(\n\t\tclear,\n\t\tnew TgdPainterState(context, {\n\t\t\tchildren: [lod],\n\t\t\tdepth: webglPresetDepth.less,\n\t\t}),\n\t)\n\tcontext.paint()\n\tnew TgdControllerCameraOrbit(context, {\n\t\tinertiaOrbit: 1000,\n\t\tinertiaZoom: 1000,\n\t})\n}"}
const FULL = "import {\n\ttype ArrayNumber3,\n\ttype ArrayNumber4,\n\tTgdCameraPerspective,\n\ttype TgdContext,\n\tTgdControllerCameraOrbit,\n\tTgdGeometrySphereIco,\n\tTgdMaterialDiffuse,\n\tTgdPainterClear,\n\tTgdPainterLOD,\n\tTgdPainterMesh,\n\tTgdPainterMeshGltf,\n\tTgdPainterNode,\n\tTgdPainterState,\n\tTgdTransfo,\n\ttgdCalcDegToRad,\n\ttgdColorMakeHueWheel,\n\twebglPresetDepth,\n} from \"@tolokoban/tgd\"\n\nimport View, { type Assets } from \"@/components/demo/Tgd\"\n\nimport BoxURL from \"./box.glb\"\n\nfunction init(context: TgdContext, assets: Assets) {\n\tconst { camera } = context\n\tif (camera instanceof TgdCameraPerspective) {\n\t\tcamera.fovy = tgdCalcDegToRad(60)\n\t\tcamera.spaceHeightAtTarget = 6\n\t}\n\tcamera.near = 1e-2\n\tcamera.far = 1e2\n\tconst clear = new TgdPainterClear(context, { color: [0.3, 0.3, 0.3, 1] })\n\tconst bbox: {\n\t\tmin: Readonly<ArrayNumber3>\n\t\tmax: Readonly<ArrayNumber3>\n\t} = {\n\t\tmin: [-1, -1, -1],\n\t\tmax: [+1, +1, +1],\n\t}\n\tconst [minX, minY, minZ] = bbox.min\n\tconst [maxX, maxY, maxZ] = bbox.max\n\tconst COLORS: ArrayNumber4[] = tgdColorMakeHueWheel({\n\t\tsteps: 8,\n\t}).map((color) => [color.R, color.G, color.B, 1] as ArrayNumber4)\n\tconst levels = [0, 1, 2, 3, 4, 5]\n\tconst materials = levels.map(\n\t\t(i) =>\n\t\t\tnew TgdMaterialDiffuse({\n\t\t\t\tlockLightsToCamera: true,\n\t\t\t\tcolor: COLORS[i],\n\t\t\t}),\n\t)\n\tconst boxes = [0, 1, 2, 3, 4, 5].map(\n\t\t(i) =>\n\t\t\tnew TgdPainterMeshGltf(context, {\n\t\t\t\tasset: assets.glb.box,\n\t\t\t\tmaterial: materials[i],\n\t\t\t}),\n\t)\n\tconst lod = new TgdPainterLOD(context, {\n\t\tbbox,\n\t\tasync factory(x: number, y: number, z: number, level: number) {\n\t\t\tconst size = 2 ** -level\n\t\t\tconst sizeX = size * (maxX - minX)\n\t\t\tconst sizeY = size * (maxY - minY)\n\t\t\tconst sizeZ = size * (maxZ - minZ)\n\t\t\tconst center: ArrayNumber3 = [\n\t\t\t\t(x + 0.5) * sizeX + minX,\n\t\t\t\t(y + 0.5) * sizeY + minY,\n\t\t\t\t(z + 0.5) * sizeZ + minZ,\n\t\t\t]\n\t\t\tconst transfo = new TgdTransfo()\n\t\t\ttransfo.setPosition(center).setScale(sizeX, sizeY, sizeZ)\n\t\t\tconst node = new TgdPainterNode({\n\t\t\t\tname: `(${x}, ${y}, ${z})/${level}`,\n\t\t\t\tchildren: [boxes[level]],\n\t\t\t\ttransfo,\n\t\t\t})\n\t\t\treturn node\n\t\t},\n\t\tsubdivisions: 5,\n\t})\n\tcontext.add(\n\t\tclear,\n\t\tnew TgdPainterState(context, {\n\t\t\tchildren: [lod],\n\t\t\tdepth: webglPresetDepth.less,\n\t\t}),\n\t)\n\tcontext.paint()\n\tnew TgdControllerCameraOrbit(context, {\n\t\tinertiaOrbit: 1000,\n\t\tinertiaZoom: 1000,\n\t})\n}\n\nexport default function Demo() {\n\treturn (\n\t\t<View\n\t\t\tonReady={init}\n\t\t\tgizmo\n\t\t\tassets={{\n\t\t\t\tglb: { box: BoxURL },\n\t\t\t}}\n\t\t/>\n\t)\n}\n"

export default function DemoContainer() {
    const [full, setFull] = React.useState(false)
    return <>
        <div className="half-left"><Demo /></div>
        <div className="half-right">
            <div>
                <ViewButton variant="elevated" onClick={() => setFull(!full)}>
                    {full ? "Show code details" : "Show full code"}
                </ViewButton>
            </div>
            <CodeViewer language="tsx" value={full ? FULL : FOCUS} />
        </div>
    </>
}