/**
 * Warning! This code has been generated automatically.
 */
import React from "react"
import { ViewButton } from "@tolokoban/ui"
import CodeViewer from "@/components/demo/CodeViewer"
import Demo from "./segments.demo"

const FOCUS = {"Detail #1":"    context.camera.transfo.distance = 50\n    new TgdControllerCameraOrbit(context, {\n        inertiaOrbit: 1000,\n        maxDistance: 50,\n        minDistance: 5,\n        speedZoom: 50,\n    })\n    const clear = new TgdPainterClear(context, {\n        color: [0.3, 0.3, 0.3, 1],\n        depth: 1,\n    })\n    const data = new TgdPainterSegmentsData()\n    const radius = 10\n    const nodes: ArrayNumber4[] = []\n    const width = 50\n    for (let step = -width; step < width; step++) {\n        const ang = step * 0.5\n        const r = radius * Math.cos((step * Math.PI * 0.5) / width)\n        const x = r * Math.cos(ang)\n        const y = step * 0.2\n        const z = r * Math.sin(ang)\n        const thickness = Math.max(0, 1.0 - Math.abs(step) / width)\n        nodes.push([x, y, z, thickness])\n    }\n    for (let i = 1; i < nodes.length; i++) {\n        const uv0: ArrayNumber2 = [(i - 0.5) / (nodes.length + 1), 0]\n        const uv1: ArrayNumber2 = [(i + 0.5) / (nodes.length + 1), 0]\n        data.add(nodes[i - 1], nodes[i], uv0, uv1)\n    }\n    const palette = new TgdTexture2D(context).loadBitmap(\n        tgdCanvasCreatePalette([\"#f44\", \"#ff4\", \"#4f4\", \"#4ff\", \"#44f\"])\n    )\n    const segments = new TgdPainterSegments(context, {\n        makeDataset: data.makeDataset,\n        roundness: 6,\n        minRadius: 4,\n        // material: new TgdMaterialDiffuse({\n        //     color: palette,\n        // }),\n        material: new TgdMaterialGhost(),\n    })\n    const state = new TgdPainterState(context, {\n        depth: webglPresetDepth.less,\n        children: [segments],\n    })\n    context.add(clear, state)\n    context.paint()"}
const FULL = "import {\n    ArrayNumber2,\n    ArrayNumber4,\n    tgdCanvasCreatePalette,\n    TgdContext,\n    TgdControllerCameraOrbit,\n    TgdMaterialDiffuse,\n    TgdMaterialGhost,\n    TgdPainterClear,\n    TgdPainterSegments,\n    TgdPainterSegmentsData,\n    TgdPainterState,\n    TgdTexture2D,\n    webglPresetDepth,\n} from \"@tolokoban/tgd\"\nimport View from \"@/components/demo/Tgd\"\n\nfunction init(context: TgdContext) {\n    context.camera.transfo.distance = 50\n    new TgdControllerCameraOrbit(context, {\n        inertiaOrbit: 1000,\n        maxDistance: 50,\n        minDistance: 5,\n        speedZoom: 50,\n    })\n    const clear = new TgdPainterClear(context, {\n        color: [0.3, 0.3, 0.3, 1],\n        depth: 1,\n    })\n    const data = new TgdPainterSegmentsData()\n    const radius = 10\n    const nodes: ArrayNumber4[] = []\n    const width = 50\n    for (let step = -width; step < width; step++) {\n        const ang = step * 0.5\n        const r = radius * Math.cos((step * Math.PI * 0.5) / width)\n        const x = r * Math.cos(ang)\n        const y = step * 0.2\n        const z = r * Math.sin(ang)\n        const thickness = Math.max(0, 1.0 - Math.abs(step) / width)\n        nodes.push([x, y, z, thickness])\n    }\n    for (let i = 1; i < nodes.length; i++) {\n        const uv0: ArrayNumber2 = [(i - 0.5) / (nodes.length + 1), 0]\n        const uv1: ArrayNumber2 = [(i + 0.5) / (nodes.length + 1), 0]\n        data.add(nodes[i - 1], nodes[i], uv0, uv1)\n    }\n    const palette = new TgdTexture2D(context).loadBitmap(\n        tgdCanvasCreatePalette([\"#f44\", \"#ff4\", \"#4f4\", \"#4ff\", \"#44f\"])\n    )\n    const segments = new TgdPainterSegments(context, {\n        makeDataset: data.makeDataset,\n        roundness: 6,\n        minRadius: 4,\n        // material: new TgdMaterialDiffuse({\n        //     color: palette,\n        // }),\n        material: new TgdMaterialGhost(),\n    })\n    const state = new TgdPainterState(context, {\n        depth: webglPresetDepth.less,\n        children: [segments],\n    })\n    context.add(clear, state)\n    context.paint()\n    context.inputs.pointer.eventHover.addListener((event) => {\n        const { x, y } = event.current\n        const [R, G, B] = context.readPixel(x, y)\n        console.log(\n            `%c(${R}, ${G}, ${B})]`,\n            `color:#777;background:rgb(${R},${G},${B})`\n        )\n    })\n}\n\nexport default function Demo() {\n    return (\n        <View\n            onReady={init}\n            gizmo\n            options={{\n                preserveDrawingBuffer: true,\n            }}\n        />\n    )\n}\n"

export default function DemoContainer() {
    const [full, setFull] = React.useState(false)
    return <>
        <div className="half-left"><Demo /></div>
        <div className="half-right">
            <div>
                <ViewButton variant="elevated" onClick={() => setFull(!full)}>
                    {full ? "Show code details" : "Show full code"}
                </ViewButton>
            </div>
            <CodeViewer language="tsx" value={full ? FULL : FOCUS} />
        </div>
    </>
}