/**
 * Warning! This code has been generated automatically.
 */
import React from "react"
import { ViewButton } from "@tolokoban/ui"
import CodeViewer from "@/components/demo/CodeViewer"
import Demo from "./framebuffer.demo"

const FOCUS = {"Detail #1":"\tcontext.camera = new TgdCameraPerspective({\n\t\ttransfo: { distance: 2 },\n\t\tfar: 100,\n\t\tnear: 0.01,\n\t\tfovy: tgdCalcDegToRad(35),\n\t\tzoom: 1,\n\t});\n\tnew TgdControllerCameraOrbit(context, {\n\t\tspeedPanning: 0,\n\t\tinertiaOrbit: 1000,\n\t\tgeo: {\n\t\t\tlat: tgdCalcDegToRad(50),\n\t\t\tminLat: tgdCalcDegToRad(-20),\n\t\t\tmaxLat: tgdCalcDegToRad(80),\n\t\t},\n\t});\n\tconst clear = new TgdPainterClear(context, {\n\t\tcolor: new TgdVec4(0, 0, 0, 1),\n\t\tdepth: 1,\n\t\tstencil: 0,\n\t});\n\tconst mesh = new TgdPainterState(context, {\n\t\tdepth: webglPresetDepth.less,\n\t\tcull: webglPresetCull.back,\n\t\tchildren: [\n\t\t\tnew TgdPainterMeshGltf(context, {\n\t\t\t\tasset: assets.glb.world,\n\t\t\t\tmaterial: ({ color }) => new MaterialDiffuse({ color }),\n\t\t\t}),\n\t\t],\n\t});\n\tconst meshOpaque = new TgdPainterState(context, {\n\t\tdepth: webglPresetDepth.less,\n\t\tcull: webglPresetCull.back,\n\t\tchildren: [\n\t\t\tnew TgdPainterMeshGltf(context, {\n\t\t\t\tasset: assets.glb.world,\n\t\t\t\tmaterial: ({ color }) => new TgdMaterialDiffuse({ color }),\n\t\t\t}),\n\t\t],\n\t});\n\tconst sea = new PainterSea(context);\n\tconst scene = new TgdPainterGroup([clear, mesh]);\n\tconst framebuffer = new TgdPainterFramebufferWithAntiAliasing(context, {\n\t\ttextureColor0: new TgdTexture2D(context),\n\t\tchildren: [scene],\n\t});\n\tif (framebuffer.textureColor0) sea.texture = framebuffer.textureColor0;\n\tcontext.add(framebuffer, clear, meshOpaque, sea);\n\tcontext.logic.add((time) => {\n\t\tsea.y = Math.sin(time * 0.4) * 0.5;\n\t});\n\tcontext.play();"}
const FULL = "import {\n\ttgdCalcDegToRad,\n\tTgdCameraPerspective,\n\ttype TgdContext,\n\tTgdControllerCameraOrbit,\n\tTgdMaterialDiffuse,\n\tTgdPainterClear,\n\tTgdPainterFramebufferWithAntiAliasing,\n\tTgdPainterGroup,\n\tTgdPainterMeshGltf,\n\tTgdPainterState,\n\tTgdTexture2D,\n\tTgdVec4,\n\twebglPresetCull,\n\twebglPresetDepth,\n} from \"@tolokoban/tgd\";\nimport View, { type Assets } from \"@/components/demo/Tgd\";\n\n// import WorldURL from \"./world.glb\"\nimport WorldURL from \"@/assets/mesh/chinese-chandelier.glb\";\nimport GridURL from \"@/assets/mesh/grid-10x10.glb\";\nimport { PainterSea } from \"./sea\";\nimport { MaterialDiffuse } from \"./diffuse\";\n\nfunction init(context: TgdContext, assets: Assets) {\n\tcontext.camera = new TgdCameraPerspective({\n\t\ttransfo: { distance: 2 },\n\t\tfar: 100,\n\t\tnear: 0.01,\n\t\tfovy: tgdCalcDegToRad(35),\n\t\tzoom: 1,\n\t});\n\tnew TgdControllerCameraOrbit(context, {\n\t\tspeedPanning: 0,\n\t\tinertiaOrbit: 1000,\n\t\tgeo: {\n\t\t\tlat: tgdCalcDegToRad(50),\n\t\t\tminLat: tgdCalcDegToRad(-20),\n\t\t\tmaxLat: tgdCalcDegToRad(80),\n\t\t},\n\t});\n\tconst clear = new TgdPainterClear(context, {\n\t\tcolor: new TgdVec4(0, 0, 0, 1),\n\t\tdepth: 1,\n\t\tstencil: 0,\n\t});\n\tconst mesh = new TgdPainterState(context, {\n\t\tdepth: webglPresetDepth.less,\n\t\tcull: webglPresetCull.back,\n\t\tchildren: [\n\t\t\tnew TgdPainterMeshGltf(context, {\n\t\t\t\tasset: assets.glb.world,\n\t\t\t\tmaterial: ({ color }) => new MaterialDiffuse({ color }),\n\t\t\t}),\n\t\t],\n\t});\n\tconst meshOpaque = new TgdPainterState(context, {\n\t\tdepth: webglPresetDepth.less,\n\t\tcull: webglPresetCull.back,\n\t\tchildren: [\n\t\t\tnew TgdPainterMeshGltf(context, {\n\t\t\t\tasset: assets.glb.world,\n\t\t\t\tmaterial: ({ color }) => new TgdMaterialDiffuse({ color }),\n\t\t\t}),\n\t\t],\n\t});\n\tconst sea = new PainterSea(context);\n\tconst scene = new TgdPainterGroup([clear, mesh]);\n\tconst framebuffer = new TgdPainterFramebufferWithAntiAliasing(context, {\n\t\ttextureColor0: new TgdTexture2D(context),\n\t\tchildren: [scene],\n\t});\n\tif (framebuffer.textureColor0) sea.texture = framebuffer.textureColor0;\n\tcontext.add(framebuffer, clear, meshOpaque, sea);\n\tcontext.logic.add((time) => {\n\t\tsea.y = Math.sin(time * 0.4) * 0.5;\n\t});\n\tcontext.play();\n}\n\nexport default function Demo() {\n\treturn (\n\t\t<View\n\t\t\toptions={{ antialias: true, stencil: true, depth: true }}\n\t\t\tonReady={init}\n\t\t\tassets={{\n\t\t\t\tglb: {\n\t\t\t\t\tworld: WorldURL,\n\t\t\t\t\tsee: GridURL,\n\t\t\t\t},\n\t\t\t}}\n\t\t/>\n\t);\n}\n"

export default function DemoContainer() {
    const [full, setFull] = React.useState(false)
    return <>
        <div className="half-left"><Demo /></div>
        <div className="half-right">
            <div>
                <ViewButton variant="elevated" onClick={() => setFull(!full)}>
                    {full ? "Show code details" : "Show full code"}
                </ViewButton>
            </div>
            <CodeViewer language="tsx" value={full ? FULL : FOCUS} />
        </div>
    </>
}