/**
 * Warning! This code has been generated automatically.
 */
import React from "react"
import { ViewButton } from "@tolokoban/ui"
import CodeViewer from "@/components/demo/CodeViewer"
import Demo from "./bloom.demo"

const FOCUS = {"Detail #1":"\tconst { camera } = context;\n\tcamera.fitSpaceAtTarget(3, 3);\n\tconst mesh = createMesh(context, assets, false);\n\tconst meshFlat = createMesh(context, assets, true);\n\tconst framebuffer = new TgdPainterFramebuffer(context, {\n\t\tviewportMatchingScale: 0.25,\n\t\tchildren: [meshFlat],\n\t\ttextureColor0: new TgdTexture2D(context, {\n\t\t\tparams: {\n\t\t\t\tminFilter: \"LINEAR\",\n\t\t\t\tmagFilter: \"LINEAR\",\n\t\t\t\twrapR: \"CLAMP_TO_EDGE\",\n\t\t\t\twrapS: \"CLAMP_TO_EDGE\",\n\t\t\t\twrapT: \"CLAMP_TO_EDGE\",\n\t\t\t},\n\t\t}),\n\t});\n\tconst filterMultiply = new TgdFilterMultiply({\n\t\tcolor: [0.5, 0.5, 0.5, 1],\n\t});\n\tconst blurSize = 16;\n\tcontext.add(\n\t\tmesh,\n\t\tframebuffer,\n\t\tnew TgdPainterState(context, {\n\t\t\tdepth: \"off\",\n\t\t\tcull: \"off\",\n\t\t\tblend: \"add\",\n\t\t\tchildren: [\n\t\t\t\tnew TgdPainterFilter(context, {\n\t\t\t\t\ttexture: framebuffer.textureColor0,\n\t\t\t\t\tflipY: true,\n\t\t\t\t\tfilters: [\n\t\t\t\t\t\t...TgdFilterBlur.createPair({ size: blurSize }),\n\t\t\t\t\t\tfilterMultiply,\n\t\t\t\t\t],\n\t\t\t\t}),\n\t\t\t],\n\t\t}),\n\t\t(time) => {\n\t\t\tconst s = Math.abs(Math.sin(time)) ** 13 * 2;\n\t\t\tfilterMultiply.color.x = s;\n\t\t\tfilterMultiply.color.y = s;\n\t\t\tfilterMultiply.color.z = s;\n\t\t},\n\t);\n\tcontext.play();"}
const FULL = "import {\n\ttype ArrayNumber4,\n\ttype TgdContext,\n\tTgdFilterBlur,\n\tTgdFilterMultiply,\n\tTgdLight,\n\tTgdMaterialDiffuse,\n\tTgdMaterialFlat,\n\tTgdPainterBackground,\n\tTgdPainterClear,\n\tTgdPainterFilter,\n\tTgdPainterFramebuffer,\n\tTgdPainterMeshGltf,\n\tTgdPainterState,\n\tTgdTexture2D,\n} from \"@tolokoban/tgd\";\nimport SuzaneURL from \"@/assets/mesh/suzanne.glb\";\nimport View, { type Assets } from \"@/components/demo/Tgd\";\n\nfunction init(context: TgdContext, assets: Assets) {\n\tconst { camera } = context;\n\tcamera.fitSpaceAtTarget(3, 3);\n\tconst mesh = createMesh(context, assets, false);\n\tconst meshFlat = createMesh(context, assets, true);\n\tconst framebuffer = new TgdPainterFramebuffer(context, {\n\t\tviewportMatchingScale: 0.25,\n\t\tchildren: [meshFlat],\n\t\ttextureColor0: new TgdTexture2D(context, {\n\t\t\tparams: {\n\t\t\t\tminFilter: \"LINEAR\",\n\t\t\t\tmagFilter: \"LINEAR\",\n\t\t\t\twrapR: \"CLAMP_TO_EDGE\",\n\t\t\t\twrapS: \"CLAMP_TO_EDGE\",\n\t\t\t\twrapT: \"CLAMP_TO_EDGE\",\n\t\t\t},\n\t\t}),\n\t});\n\tconst filterMultiply = new TgdFilterMultiply({\n\t\tcolor: [0.5, 0.5, 0.5, 1],\n\t});\n\tconst blurSize = 16;\n\tcontext.add(\n\t\tmesh,\n\t\tframebuffer,\n\t\tnew TgdPainterState(context, {\n\t\t\tdepth: \"off\",\n\t\t\tcull: \"off\",\n\t\t\tblend: \"add\",\n\t\t\tchildren: [\n\t\t\t\tnew TgdPainterFilter(context, {\n\t\t\t\t\ttexture: framebuffer.textureColor0,\n\t\t\t\t\tflipY: true,\n\t\t\t\t\tfilters: [\n\t\t\t\t\t\t...TgdFilterBlur.createPair({ size: blurSize }),\n\t\t\t\t\t\tfilterMultiply,\n\t\t\t\t\t],\n\t\t\t\t}),\n\t\t\t],\n\t\t}),\n\t\t(time) => {\n\t\t\tconst s = Math.abs(Math.sin(time)) ** 13 * 2;\n\t\t\tfilterMultiply.color.x = s;\n\t\t\tfilterMultiply.color.y = s;\n\t\t\tfilterMultiply.color.z = s;\n\t\t},\n\t);\n\tcontext.play();\n}\n\nexport default function Demo() {\n\treturn (\n\t\t<View\n\t\t\tonReady={init}\n\t\t\toptions={{\n\t\t\t\talpha: false,\n\t\t\t\tpreserveDrawingBuffer: false,\n\t\t\t}}\n\t\t\tassets={{\n\t\t\t\tglb: {\n\t\t\t\t\tsuzane: SuzaneURL,\n\t\t\t\t},\n\t\t\t}}\n\t\t\tcontroller={{\n\t\t\t\tinertiaOrbit: 1000,\n\t\t\t}}\n\t\t/>\n\t);\n}\n\nfunction createMesh(context: TgdContext, assets: Assets, flat: boolean) {\n\tconst clear = new TgdPainterClear(context, {\n\t\tcolor: [0, 0, 0, 1],\n\t\tdepth: 1,\n\t});\n\tconst color: ArrayNumber4 = [0.9, 0.6, 0.1, 1];\n\tconst mesh = new TgdPainterMeshGltf(context, {\n\t\tasset: assets.glb.suzane,\n\t\tmaterial: flat\n\t\t\t? new TgdMaterialFlat({ color: [0.3, 0.6, 0.9, 1] })\n\t\t\t: new TgdMaterialDiffuse({\n\t\t\t\t\tcolor,\n\t\t\t\t\tlockLightsToCamera: true,\n\t\t\t\t}),\n\t});\n\treturn new TgdPainterState(context, {\n\t\tdepth: \"less\",\n\t\tblend: \"off\",\n\t\tcull: \"back\",\n\t\tchildren: [\n\t\t\tclear,\n\t\t\tmesh,\n\t\t\t(time) => {\n\t\t\t\tmesh.transfo.setEulerRotation(time * 5, time * 7.124, time * -3.085);\n\t\t\t},\n\t\t],\n\t});\n}\n"

export default function DemoContainer() {
    const [full, setFull] = React.useState(false)
    return <>
        <div className="half-left"><Demo /></div>
        <div className="half-right">
            <div>
                <ViewButton variant="elevated" onClick={() => setFull(!full)}>
                    {full ? "Show code details" : "Show full code"}
                </ViewButton>
            </div>
            <CodeViewer language="tsx" value={full ? FULL : FOCUS} />
        </div>
    </>
}